version: "3"

services:
    db:
        image: postgres:14.1-alpine
        ports:
            - 5433:5432
        container_name: ecommerce-poc
        environment:
            POSTGRES_USER: app
            POSTGRES_PASSWORD: password
            POSTGRES_DB: ecommerce-poc
            POSTGRES_HOST_AUTH_METHOD: trust
        volumes:
            - postgres_data_container:/var/lib/postgresql/data
volumes:
    postgres_data_container:
        driver: local
